version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: fws-barber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 915sq9fwogxEc7Qi
      POSTGRES_PORT: 5434
    ports:
      - "5434:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
